services:
  lgtm:
    image: grafana/otel-lgtm:0.7.6
    container_name: operator-grafana-lgtm
    ports:
      - "3000:3000"   # Grafana
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver

  fakes:
    container_name: operator-fakes
    build:
      dockerfile: Dockerfile.fakes
    ports:
      - "8050:8050" # Maskinporten API
      - "8051:8051" # Maskinporten self service API
      - "8052:8052" # Org Registry API
