apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
replacements:
- source:
    kind: Deployment
    name: altinn-mcp-server
    fieldPath: metadata.annotations.[altinn.studio/image]
  targets:
  - select:
      kind: Deployment
      name: altinn-mcp-server
    fieldPaths:
      - spec.template.spec.containers.[altinn-mcp-server].image
