apiVersion: v1
kind: Service
metadata:
  name: altinn-mcp-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8069
      protocol: TCP
      name: http
  selector:
    app: altinn-mcp-server
