apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: altinn-studio-gateway-sa
  namespace: grafana
spec:
  instanceName: 'external-grafana'
  isDisabled: false
  name: altinn-studio-gateway-sa
  role: Editor
  suspend: false
  tokens:
    - name: studio-gateway
      secretName: studio-gateway-grafana-token
