apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: altinn-studio-gateway-sa
  namespace: runtime-gateway
spec:
  name: 'altinn-studio-gateway-sa'
  role: Editor
  isDisabled: false
  instanceName: 'external-grafana'
  tokens:
    - name: 'studio-gateway'
      secretName: studio-gateway-grafana-token
