apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - ingressroute.yaml
  - secrets.yaml
  - role.yaml
  - rolebinding.yaml
replacements:
  - source:
      kind: Deployment
      name: gateway
      fieldPath: metadata.annotations.[altinn.studio/image]
    targets:
      - select:
          kind: Deployment
          name: gateway
        fieldPaths:
          - spec.template.spec.containers.[name=gateway].image
