version: '3.6'

networks:
  altinntestlocal_network:
    external: false

services:
  localtest_loadbalancer:
    container_name: localtest-loadbalancer
    image: localtest-loadbalancer:latest
    restart: always
    networks:
      - altinntestlocal_network
    ports:
      - "${ALTINN3LOCAL_PORT:-80}:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - SUB_FILTER=${SUB_FILTER:-}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    build:
      context: ./loadbalancer
  altinn_platform_pdf:
    container_name: altinn-pdf
    image: altinn-pdf:latest
    restart: always
    networks:
      - altinntestlocal_network
    ports:
     - "5070:5070"
    build:
      context: ./../Altinn.Platform/Altinn.Platform.PDF/
  altinn_localtest:
    container_name: localtest
    image: localtest:latest
    restart: always
    networks:
      - altinntestlocal_network
    ports:
      - "5101:5101"
    build:
      dockerfile: ./LocalTest/Dockerfile
      context: ./
    environment:
      - DOTNET_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://*:5101/
      - GeneralSettings__BaseUrl=http://altinn3local.no:${ALTINN3LOCAL_PORT:-80}
    volumes:
      - ${ALTINN3LOCALSTORAGE_PATH:-AltinnPlatformLocal}:/AltinnPlatformLocal

volumes:
  AltinnPlatformLocal: