apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - alert-rules
#  - contact-points
  - dashboards
#  - notifcation-policies
#  - notifcation-templates
#  - service-accounts
