apiVersion: apps/v1
kind: Deployment
metadata:
  name: altinn-designer
spec:
  selector:
    matchLabels:
      run: altinn-designer
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: altinn-designer
    spec:
      nodeSelector:
        altinn-designer: "true"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ required "image.tag not set" .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.image.containerPort }}
          {{- if eq (required "evironment not set" .Values.environment) "development"}}
          env:
            {{- range $variable := .Values.environmentVariables.development }}
            - name: {{ $variable.name }}
              {{- if $variable.value }}
              value: {{ $variable.value}}
              {{- end }}
              {{- if $variable.valueFrom }}
              valueFrom:
                {{- if $variable.valueFrom.secretKeyRef}}
                secretKeyRef:
                  name: {{ $variable.valueFrom.secretKeyRef.name }}
                  key: {{ $variable.valueFrom.secretKeyRef.key }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if eq (required "evironment not set" .Values.environment) "production"}}
          env:
            {{- range $variable := .Values.environmentVariables.production }}
            - name: {{ $variable.name }}
              {{- if $variable.value }}
              value: {{ $variable.value}}
              {{- end }}
              {{- if $variable.valueFrom }}
              valueFrom:
                {{- if $variable.valueFrom.secretKeyRef}}
                secretKeyRef:
                  name: {{ $variable.valueFrom.secretKeyRef.name }}
                  key: {{ $variable.valueFrom.secretKeyRef.key }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.volumeMounts}}
          volumeMounts:
            {{- range $mount := .Values.volumeMounts}}
            - name: {{ $mount.name }}
              mountPath: {{ $mount.mountPath }}
            {{- end }}
          {{- end }}
        {{- if .Values.volumes }}
      volumes:
      {{- range $volume := .Values.volumes }}
        - name: {{ $volume.name }}
          {{- if $volume.persistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ $volume.persistentVolumeClaim.claimName }}
          {{- end }}
          {{- if $volume.secret }}
          secret:
            secretName: {{ $volume.secret.secretName }}
          {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.image.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecret }}
      {{- end }}
