apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - ../base

patches:
  - path: patches/router-config.yaml
  - path: patches/gateway-config.yaml
  - path: patches/gateway-secrets.yaml
