apiVersion: v1
kind: Service
metadata:
  name: fakes
  namespace: runtime-operator
spec:
  type: ClusterIP
  ports:
  - name: maskinporten-api
    port: 8050
    targetPort: 8050
  - name: self-service-api
    port: 8051
    targetPort: 8051
  - name: org-registry-api
    port: 8052
    targetPort: 8052
  selector:
    app: fakes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakes
  namespace: runtime-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakes
  template:
    metadata:
      labels:
        app: fakes
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: fakes
        image: localhost:5001/runtime-operator-fakes:latest
        imagePullPolicy: Always
        env:
        - name: OPERATOR_CONFIG_FILE
          value: /config/config.env
        ports:
        - name: maskinporten
          containerPort: 8050
        - name: selfservice
          containerPort: 8051
        - name: orgregistry
          containerPort: 8052
        livenessProbe:
          httpGet:
            path: /health
            port: 8050
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8050
          initialDelaySeconds: 3
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - name: operator-config
          mountPath: /config
          readOnly: true
      volumes:
      - name: operator-config
        configMap:
          name: operator-operator-config
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fakes-strip-prefix
  namespace: runtime-operator
spec:
  stripPrefix:
    prefixes:
    - /fakes
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fakes-ingress
  namespace: runtime-operator
spec:
  entryPoints:
  - traefik
  routes:
  - kind: Rule
    match: PathPrefix(`/fakes`)
    services:
    - name: fakes
      port: 8051
    middlewares:
    - name: fakes-strip-prefix
