apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
  - fakes.yaml
patches:
  - path: operator-config-patch.yaml
  # - Patch image
  - target:
      kind: Deployment
      name: operator-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "localhost:5001/runtime-operator-controller:latest"
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: "Always"
