apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - networkpolicy.yaml
replacements:
- source:
    kind: Deployment
    name: studio-gateway
    fieldPath: metadata.annotations.[altinn.studio/image]
  targets:
  - select:
      kind: Deployment
      name: studio-gateway
    fieldPaths:
      - spec.template.spec.containers.[name=studio-gateway].image