services:
  workflow-engine:
    build:
      context: ../
      dockerfile: workflow-engine/Dockerfile
    container_name: workflow-engine-api
    networks:
      - workflow-engine-network
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: workflow-engine-postgres
    environment:
      POSTGRES_DB: workflow_engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      TZ: Europe/Oslo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - workflow-engine-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: workflow-engine-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@altinn.no
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - workflow-engine-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./.docker/servers.json:/pgadmin4/servers.json

  lgtm:
    image: grafana/otel-lgtm:0.17.0
    container_name: workflow-engine-lgtm
    restart: unless-stopped
    networks:
      - workflow-engine-network
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    volumes:
      - ./.docker/grafana-datasources.yml:/etc/grafana/provisioning/datasources/postgres.yml:ro

volumes:
  postgres_data:
  pgadmin_data:

networks:
  workflow-engine-network:
    driver: bridge
