apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: external-grafana-altinn-studio-gateway
  namespace: grafana
spec:
  name: altinn-studio-gateway
  type: webhook
  instanceSelector:
    matchLabels:
      dashboards: external-grafana
  settings:
    httpMethod: POST
  valuesFrom:
    - targetPath: url
      valueFrom:
        secretKeyRef:
          name: external-grafana-altinn-studio-gateway-url
          key: url
    - targetPath: token
      valueFrom:
        secretKeyRef:
          name: external-grafana-altinn-studio-gateway-token
          key: token
