apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: altinn-studio-slack
spec:
  name: Altinn Studio Slack
  type: slack
  instanceSelector:
    matchLabels:
      dashboards: 'external-grafana'
  settings:
    text: '{{ template "slack.message" . }}'
    title: '{{ template "slack.default.title" . }}'
    disableResolveMessage: true
  valuesFrom:
    - targetPath: 'settings.webhookUrl'
      valueFrom:
        secretKeyRef:
          name: slack-webhook
          key: url
