apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-environment
data:
  GATEWAY_URL: "https://${SERVICEOWNER_ID}.apps.altinn.no/runtime/gateway/api/v1/alerts"
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
vars:
  - name: GATEWAY_URL
    objref:
      kind: ConfigMap
      name: grafana-environment
      apiVersion: v1
    fieldref:
      fieldpath: data.GATEWAY_URL
