apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  # - Add TEST_INTERNALS_MODE environment variable for local/test environment
  # - Set image and image pull policy
  # - Set browser restart interval for local testing
  - target:
      kind: Deployment
      name: pdf3-worker
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: TEST_INTERNALS_MODE
          value: "true"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PDF3_BROWSER_RESTART_INTERVAL
          value: "2m"
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "localhost:5001/runtime-pdf3-worker:latest"
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: "Always"
  - target:
      kind: Deployment
      name: pdf3-proxy
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: TEST_INTERNALS_MODE
          value: "true"
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "localhost:5001/runtime-pdf3-proxy:latest"
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: "Always"
