global:
  scrape_interval: 15s

scrape_configs:
  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: health
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://workflow-engine-api:8080/api/v1/health/live
          - http://workflow-engine-api:8080/api/v1/health/ready
          - http://workflow-engine-api:8080/api/v1/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: workflow-engine-blackbox:9115
