# permissions for end users to view maskinportenclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: altinn-studio-operator
    app.kubernetes.io/managed-by: kustomize
  name: maskinportenclient-viewer-role
rules:
- apiGroups:
  - resources.altinn.studio
  resources:
  - maskinportenclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resources.altinn.studio
  resources:
  - maskinportenclients/status
  verbs:
  - get
