apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: altinn-studio-operator
    app.kubernetes.io/managed-by: kustomize
  annotations:
    azure.workload.identity/client-id: "${OPERATOR_ENTRA_CLIENT_ID}"
  # NOTE: the name of this SA can't change, it is referenced in platform terraform (where the client ID is also passed from)
  name: controller-manager
  namespace: system
