networks:
  altinntestlocal_network:
    external: false

services:
  altinn_pdf3:
    container_name: localtest-pdf3
    image: localtest-pdf3:latest
    build:
      context: ../pdf3
      dockerfile: Dockerfile.worker
    restart: always
    networks:
      - altinntestlocal_network
    ports:
      - '5300:5031'
    environment:
      - TZ=Europe/Oslo
      - PDF3_ENVIRONMENT=localtest
      - PDF3_QUEUE_SIZE=3
    extra_hosts:
      - '${TEST_DOMAIN:-local.altinn.cloud}:host-gateway'
      - 'host.containers.internal:host-gateway'

  altinn_localtest:
    container_name: localtest
    image: localtest:latest
    restart: always
    networks:
      - altinntestlocal_network
    ports:
      - '${ALTINN3LOCAL_PORT:-80}:5101'
      - '5101:5101'
    build:
      context: .
    environment:
      - DOTNET_ENVIRONMENT=Docker
      - GeneralSettings__BaseUrl=http://${TEST_DOMAIN:-local.altinn.cloud}:${ALTINN3LOCAL_PORT:-80}
      - GeneralSettings__HostName=${TEST_DOMAIN:-local.altinn.cloud}
    volumes:
      - ./testdata:/testdata
      - ${ALTINN3LOCALSTORAGE_PATH:-AltinnPlatformLocal}:/AltinnPlatformLocal
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  monitoring_otel_collector:
    container_name: monitoring_otel_collector
    image: otel/opentelemetry-collector-contrib:0.98.0
    restart: always
    networks:
      - altinntestlocal_network
    command:
      - --config=/etc/otel-collector.yaml
    volumes:
      - ./infra/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - '4317:4317' # OTLP gRPC receiver
    profiles: ['monitoring']
    depends_on:
      - monitoring_mimir
      - monitoring_tempo
      - monitoring_loki

  monitoring_tempo:
    container_name: monitoring_tempo
    image: grafana/tempo:2.4.1
    restart: always
    networks:
      - altinntestlocal_network
    command:
      - -config.file=/etc/tempo.yaml
      - -log.level=error
    volumes:
      - ./infra/tempo.yaml:/etc/tempo.yaml
    profiles: ['monitoring']

  monitoring_mimir:
    container_name: monitoring_mimir
    image: grafana/mimir:2.12.0
    restart: always
    networks:
      - altinntestlocal_network
    command:
      - -config.file=/etc/mimir.yaml
      - -target=all
      - -log.level=error
    volumes:
      - ./infra/mimir.yaml:/etc/mimir.yaml
    profiles: ['monitoring']

  monitoring_loki:
    container_name: monitoring_loki
    image: grafana/loki:3.0.0
    restart: always
    networks:
      - altinntestlocal_network
    command:
      - -config.file=/etc/loki.yaml
      - -target=all
      - -log.level=error
    volumes:
      - ./infra/loki.yaml:/etc/loki.yaml
    profiles: ['monitoring']

  monitoring_grafana:
    container_name: monitoring_grafana
    image: grafana/grafana:10.4.2
    restart: always
    networks:
      - altinntestlocal_network
    volumes:
      - ./infra/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./infra/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./infra/grafana-dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE="traceqlEditor traceToMetrics metricsSummary"
      - GF_LOG_LEVEL=error
      - GF_SERVER_DOMAIN=${TEST_DOMAIN:-local.altinn.cloud}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    profiles: ['monitoring']
    depends_on:
      - monitoring_otel_collector
      - monitoring_mimir
      - monitoring_tempo
      - monitoring_loki

  altinn_test_apps:
    container_name: altinn-test-apps
    profiles: ['test-apps']
    build:
      context: ../../..
      dockerfile: src/test/apps/Dockerfile
    restart: always
    networks:
      - altinntestlocal_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${TEST_DOMAIN:-local.altinn.cloud}:host-gateway'
    environment:
      - TZ=Europe/Oslo
      - ASPNETCORE_ENVIRONMENT=Development
      - AppSettings__OpenIdWellKnownEndpoint=http://altinn_localtest:5101/authentication/api/v1/openid/
      - PlatformSettings__ApiStorageEndpoint=http://altinn_localtest:5101/storage/api/v1/
      - PlatformSettings__ApiRegisterEndpoint=http://altinn_localtest:5101/register/api/v1/
      - PlatformSettings__ApiProfileEndpoint=http://altinn_localtest:5101/profile/api/v1/
      - PlatformSettings__ApiAuthenticationEndpoint=http://altinn_localtest:5101/authentication/api/v1/
      - PlatformSettings__ApiAuthorizationEndpoint=http://altinn_localtest:5101/authorization/api/v1/
      - PlatformSettings__ApiAccessManagementEndpoint=http://altinn_localtest:5101/accessmanagement/api/v1/
      - PlatformSettings__ApiEventsEndpoint=http://altinn_localtest:5101/events/api/v1/
      - PlatformSettings__ApiPdf2Endpoint=http://host.docker.internal:5300/pdf
    depends_on:
      - altinn_localtest

volumes:
  AltinnPlatformLocal:
