apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
configMapGenerator:
  - name: fake-oidc-config
    files:
      - openid-configuration.json
      - jwks.json
    options:
      disableNameSuffixHash: true
