apiVersion: v1
kind: Service
metadata:
  name: lhci-server
  labels:
    app: lhci-server
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: http
  selector:
    app: lhci-server
