apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: external-grafana-altinn-studio
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: 'external-grafana'
  title: Altinn Studio
