version: '3.4'

networks:
  altinnplatform_network:
    external: false

services:
  altinn_receipt_react_app:
    container_name: altinn-receipt-react-app
    image: altinn-receipt-react-app:latest
    build:
      context: ../../
      dockerfile: Altinn.Apps/AppFrontend/react/receipt/Dockerfile

  altinn_platform_receipt:
    container_name: altinn-platform-receipt
    image: altinn-platform-receipt:latest
    restart: always
    networks:
      - altinnplatform_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5060
      - PlatformSettings:ApiProfileEndpoint=https://platform.at22.altinn.cloud/profile/api/v1/
      - PlatformSettings:ApiAuthenticationEndpoint=https://platform.at22.altinn.cloud/authentication/api/v1/
      - GeneralSettings:OpenIdWellKnownEndpoint=http://localhost:5040/authentication/api/v1/openid/
      - GeneralSettings:Hostname=at22.altinn.cloud
      - GeneralSettings:RuntimeCookieName=AltinnStudioRuntime
      - GeneralSettings:LanguageFilesLocation=Languages/
    ports:
      - "5060:5060"
    depends_on:
      - altinn_receipt_react_app
    build:
      context: ../../../
      dockerfile: src/Altinn.Platform/Altinn.Platform.Receipt/Receipt/Dockerfile
