apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: apps-runtime-config-repo
  namespace: default
spec:
  interval: 5m
  provider: azure
  ref:
    tag: ${UPGRADE_CHANNEL}
  timeout: 5m
  url: oci://altinncr.azurecr.io/studio-apps/runtime-apps-runtime-config-repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-runtime-config
  namespace: default
spec:
  targetNamespace: default
  interval: 5m
  retryInterval: 5m
  timeout: 1m
  prune: true
  force: false
  wait: true
  path: ./${ENVIRONMENT}
  sourceRef:
    kind: OCIRepository
    name: apps-runtime-config-repo
    namespace: default
  postBuild:
    substitute:
      ENVIRONMENT: ${ENVIRONMENT}
