apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-config-repo
  namespace: flux-system
spec:
  interval: 5m
  provider: azure
  ref:
    tag: ${UPGRADE_CHANNEL}
  timeout: 5m
  url: oci://altinncr.azurecr.io/studio-apps/runtime-flux-config-repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-config
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 5m
  retryInterval: 5m
  timeout: 1m
  prune: true
  force: false
  wait: true
  path: ./
  sourceRef:
    kind: OCIRepository
    name: flux-config-repo
    namespace: flux-system
  postBuild:
    substitute:
      SERVICEOWNER_ID: ${SERVICEOWNER_ID}
      ENVIRONMENT: ${ENVIRONMENT}
