apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps-runtime-config.yaml
  - pdf3.yaml
  - operator.yaml
  - pdf.yaml
  - studio-gateway.yaml
  - flux-config.yaml
  - altinn-charts.yaml
  - apps-syncroot.yaml
  - observability.yaml
