name: App Frontend - Cypress

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/App/backend/**'
      - 'src/App/codelists/**'
      - 'src/App/fileanalyzers/**'
      - 'src/Runtime/localtest/**'
      - 'src/Runtime/pdf3/**'
      - 'src/App/frontend/src/**'
      - 'src/App/frontend/test/**'
      - 'src/App/frontend/yarn.lock'
      - 'src/test/apps/**'
      - '.github/workflows/app-frontend-cypress.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Build frontend
        uses: ./.github/actions/app-build-frontend

  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Build localtest
        uses: ./.github/actions/app-build-localtest
        with:
          docker-profile: test-apps

  cypress-run-internal:
    name: Cypress Run Internal
    if: |
      github.repository_owner == 'Altinn' &&
      (github.event_name != 'pull_request' && github.event.repository.fork == false) ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [build-frontend, build-docker-images]
    defaults:
      run:
        working-directory: src/App/frontend/
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6]
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Download the build folder
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: app-frontend-dist
          path: src/App/frontend/dist

      - name: Pull docker images from registry
        run: |
          # Pull the images that were built and cached in the previous job
          docker compose -f src/Runtime/localtest/docker-compose.yml --profile test-apps pull || true

      - name: Start localtest
        working-directory: src/Runtime/localtest
        run: docker compose --profile test-apps up -d

      - name: Set Percy command based on PR draft status or main branch
        shell: bash
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ] || [ "${{ github.event.pull_request.draft }}" == "false" ]; then
            echo "PERCY_COMMAND=percy exec --parallel -- npx" >> $GITHUB_ENV
          fi

      - name: Cypress run
        env:
          CYPRESS_PROJECT_ID: o7mikf
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # CYPRESS_RECORD_KEY comes from "org secrets"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_PARALLEL_TOTAL: 6
          PERCY_PARALLEL_NONCE: ${{ github.run_id }}-${{ github.run_attempt }}
          PERCY_BRANCH: ${{ github.head_ref || github.ref_name }}
          PERCY_TARGET_BRANCH: ${{ github.base_ref || 'main' }}
          IS_PR_DRAFT: ${{ github.event.pull_request.draft }}
        uses: cypress-io/github-action@7ef72e250a9e564efb4ed4c2433971ada4cc38b4 # v6
        with:
          # quote the url to be safe against YML parsing surprises
          working-directory: src/App/frontend/
          start: 'npx http-server dist --cors="*" -p 8080'
          wait-on: 'http://localhost:8080'
          command-prefix: ${{ env.PERCY_COMMAND }}
          record: true
          parallel: true
          group: altinn-app-frontend
          tag: altinn-app-frontend
          browser: chrome
          ci-build-id: ${{ github.run_id }}-${{ github.run_attempt }}
          spec: test/e2e/integration
          env: environment=docker

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: app-frontend-logs
          path: src/App/frontend/test/logs/*

      - name: Stop localtest
        working-directory: src/Runtime/localtest
        run: docker compose down

  cypress-run-external:
    name: Cypress Run External
    if: |
      github.repository_owner == 'Altinn' &&
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    runs-on: ubuntu-latest
    needs: [build-frontend, build-docker-images]
    defaults:
      run:
        working-directory: src/App/frontend/

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Download the build folder
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: app-frontend-dist
          path: src/App/frontend/dist

      - name: Pull docker images from registry
        run: |
          # Pull the images that were built and cached in the previous job
          docker compose -f src/Runtime/localtest/docker-compose.yml --profile test-apps pull || true

      - name: Start localtest
        working-directory: src/Runtime/localtest
        run: docker compose --profile test-apps up -d

      - name: Cypress run
        uses: cypress-io/github-action@7ef72e250a9e564efb4ed4c2433971ada4cc38b4 # v6
        with:
          working-directory: src/App/frontend/
          start: 'npx http-server dist --cors="*" -p 8080'
          browser: chrome
          spec: test/e2e/integration
          env: environment=docker

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: app-frontend-external-logs
          path: |
            src/App/frontend/test/logs/*
            src/App/frontend/test/screenshots/*
            src/App/frontend/test/videos/*

      - name: Stop localtest
        if: always()
        working-directory: src/Runtime/localtest
        run: docker compose down
