name: App Template - docker build on PR

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/App/template/**'
      - '.github/workflows/app-template-build-on-pr.yaml'
  workflow_dispatch:

jobs:
  analyze:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Run release and docker build
    runs-on: ${{ matrix.os}}
    env:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Make template release
        run: |
          rsync . -rv --exclude-from=.releaseignore --exclude-from=.gitignore app-template-release
        working-directory: src/App/template/src

      - name: Docker build release
        run: |
          docker build .
        working-directory: src/App/template/src/app-template-release
