name: App Backend - Verify formatting

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/App/backend/**'
      - '.github/workflows/app-backend-formatting.yml'

jobs:
  verify-no-changes:
    if: |
      github.event.pull_request.user.login != 'renovate[bot]'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/App/backend/

    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: 8.0.x
    - name: Install csharpier
      run: dotnet tool restore
    - name: Run csharpier
      run: dotnet csharpier check .
