name: App Codelists - Build and test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/App/codelists/**'
      - '.github/workflows/app-codelists-tests.yml'
  workflow_dispatch:

jobs:
  analyze:
    strategy:
      matrix:
        os:
          - id: ubuntu-latest
            workingDir: src/App/codelists/
          - id: macos-latest
            workingDir: src/App/codelists/
          - id: windows-latest
            workingDir: src\App\codelists\
    name: Run dotnet build and test
    runs-on: ${{ matrix.os.id }}
    env:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
    steps:
      - name: Enable long paths for git on Windows
        if: matrix.os.id == 'windows-latest'
        run: git config --system core.longpaths true
      - name: Setup .NET
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
        with:
          dotnet-version: |
            8.0.x
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build
        working-directory: ${{ matrix.os.workingDir }}
        run: |
           dotnet build Altinn.Codelists.sln -v m
      - name: Test
        working-directory: ${{ matrix.os.workingDir }}
        run: |
           dotnet test Altinn.Codelists.sln -v m
