name: Designer Backend - Build and test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/Designer/backend/**'
      - 'src/Designer/testdata/**'
      - 'src/App/template/**'
      - '.github/workflows/designer-backend-dotnet-test.yaml'
  workflow_dispatch:

jobs:
  analyze:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    name: Run dotnet build and test
    runs-on: ${{ matrix.os}}
    env:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
    steps:
      - name: Enable long paths for git on Windows
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: |
            9.0.x
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build
        run: |
          dotnet build backend/Designer.sln -v m
        working-directory: src/Designer
      - name: Test
        run: |
          dotnet test backend/Designer.sln --filter FullyQualifiedName~AppDevelopmentController --no-build || exit 1;
          dotnet test backend/Designer.sln --filter FullyQualifiedName~PolicyControllerTests --no-build || exit 1;
          dotnet test backend/Designer.sln --filter FullyQualifiedName~PreviewController --no-build || exit 1;
          dotnet test backend/Designer.sln --filter FullyQualifiedName~DataModelsController --no-build || exit 1;
          dotnet test backend/Designer.sln --filter FullyQualifiedName~ResourceAdminController --no-build || exit 1;
          dotnet test backend/Designer.sln --filter FullyQualifiedName~TextController --no-build || exit 1;
          dotnet test backend/Designer.sln --filter "(Category!=GiteaIntegrationTest)&(FullyQualifiedName~RepositoryController)" --no-build || exit 1;
          dotnet test backend/Designer.sln --filter "(Category!=GiteaIntegrationTest)&(Category!=DbIntegrationTest)&(FullyQualifiedName!~AppDevelopmentController)&(FullyQualifiedName!~PreviewController)&(FullyQualifiedName!~PolicyControllerTests)&(FullyQualifiedName!~DataModelsController)&(FullyQualifiedName!~ResourceAdminController)&(FullyQualifiedName!~TextController)&(FullyQualifiedName!~RepositoryController)" -v m --no-build
        working-directory: src/Designer
