name: Designer Backend - Gitea and Db integration tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/Designer/backend/**'
      - 'src/Designer/testdata/**'
      - 'src/gitea/**'
      - '.github/workflows/designer-backend-gitea-and-db-integration-tests.yaml'
  workflow_dispatch:

jobs:
  gitea-and-db-integration-tests:
    name: Run integration tests against actual gitea and dbs
    runs-on: ubuntu-latest
    env:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: |
            9.0.x
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Build
        run: |
           dotnet build backend/Designer.sln -v m
        working-directory: src/Designer

      - name: Run integration tests
        run: |
           dotnet test backend/Designer.sln --filter "(Category=GiteaIntegrationTest)|(Category=DbIntegrationTest)" -v m
        working-directory: src/Designer
