name: Resource admin playwright tests on pr
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/resourceadm/**'
      - '.github/workflows/run-playwright-resourceadm-on-pr.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright-tests:
    name: Build environment and run e2e test
    timeout-minutes: 25
    runs-on: ubuntu-latest

    steps:
      - name: 'Checking Out Code'
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Generate .env file
        run: |
          echo PLAYWRIGHT_TEST_APP=autodeploy-v3 >> .env
          echo DEVELOP_APP_DEVELOPMENT=0 >> .env
          echo DEVELOP_RESOURCE_ADMIN=0 >> .env
          echo DEVELOP_BACKEND=0 >> .env
          echo DEVELOP_DASHBOARD=0 >> .env
          echo DEVELOP_PREVIEW=0 >> .env
          echo GITEA_ADMIN_PASS=g9wDIG@6gf >> .env
          echo GITEA_ADMIN_USER=localg1iteaadmin >> .env
          echo GITEA_CYPRESS_USER=cypress_testuser >> .env
          echo GITEA_CYPRESS_PASS=g9wDIG@6gf >> .env
          echo GITEA_ORG_USER=ttd >> .env
          echo POSTGRES_PASSWORD=kyeDIG@eip >> .env
          echo COMMIT= >> .env
          echo IGNORE_DOCKER_DNS_LOOKUP=true >> .env

      - name: Run setup.js script
        run: |
          node ./development/setup.js

      - name: 'Installing Dependencies'
        uses: ./.github/actions/yarn-install

      - name: Playwright resourceadm run
        working-directory: frontend/resourceadm/testing/playwright
        env:
          environment: local
        run: |
          yarn resourceadm:setup:playwright
          yarn resourceadm:playwright:test:all

      - name: Store artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: playwright-resourceadm-screenshots
          path: frontend/resourceadm/testing/playwright/test-results
