name: K8s wrapper - Build

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'src/Runtime/kubernetes-wrapper/**'
      - '.github/workflows/runtime-kubernetes-wrapper-integrationtests-kind.yaml'
  workflow_dispatch:

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: src/Runtime/kubernetes-wrapper

    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: |
          10.0.x

    - name: Restore tools
      run: dotnet tool restore

    - name: Formatting
      run: dotnet csharpier check .

    - name: Test
      run: make test

    - name: Test E2E
      run: make test-e2e
